### ISSUE TITLE
flexible SnisOcsApp equipment configuration

### ISSUE THREAD

**Issue by EastEriq** [blumzi/LAST_WebApi#7]
instead of just creating an `obs.SnisOcsApp` object reflecting the current subdivision of equipment in the LAST unit (twin computers e and w, mount almost always on e, 2 cameras and focusers on each, two power switches).

Why, because for the time being we may have test rigs with different configurations (e.g. "units" based on a single computer, with only part of the equipment available being tested), and in future we'd want to use the same mechanics for different projects. Even thinking at PAST, a mount may carry less than 4 telescopes.

In fact mastrolindo's `obs.unitCS` currently allows, via configurations, an arbitrary number of local or remote focusers, cameras and switches, using different hardware drivers [to be fair, in webapi_transition the hierarchy is fixed, but the hardware drivers are indeed specified in configurations].

I completely agree that overgeneralizing is futile, as it is, at this stage, to speculate of different unit hierarchies.

**Comment by blumzi** [comment]
As soon as the unit driver is viable to some extent we should have the SnisOcsApp only makeApi for the unit and let that do its thing according to config files.  Isn't that what we were thinking?

**Comment by blumzi** [comment]
Obsolete since we no longer use SNIS.
