### ISSUE TITLE
address already in use when restarting Snis

### ISSUE THREAD

**Issue by EastEriq** [blumzi/LAST_WebApi#8]
While developing, I'm frequently stopping and restarting obs.SnisOCS on last11e, sometimes after having succesfully talked to it from last12w. I stop nicely SnisOCS by closing the small figure window. I get frequently this error at restart, after all wrapped classes and semaphores have been created: 

```
Error using Simple.Net.Networking.JavaTcpServer (line 12)
Java exception occurred:
java.net.BindException: Address already in use (Bind failed)
	at java.net.PlainSocketImpl.socketBind(Native Method)
	at
        java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
        	at
        java.net.ServerSocket.bind(ServerSocket.java:375)
	at java.net.ServerSocket.<init>(ServerSocket.java:237)
	at java.net.ServerSocket.<init>(ServerSocket.java:128)
Error in Simple.Net.Networking.JavaSocketWrapper/start (line 31)
            this.tcpListener =
            Simple.Net.Networking.JavaTcpServer('initialize', [],
            this.server.config.port, this.server.config);
Error in Simple.Net.HttpServer/start (line 121)
            this.networker.start();
Error in obs.SnisOCS (line 25)
server.start().listen(); 
```
The only way to resume, which I found, is so close the matlab session and restart it. Would there be a nicer way to free the port when quitting SnisOCS?

**Comment by EastEriq** [comment]
I can't predictably reproduce this. I just tried starting and shutdown a number of times without problems. I also tried without and with connecting instruments, without and with entering the debugger (which I often do developing), without and with sending commands which generate matlab errors on the server side.

**Comment by EastEriq** [comment]
Seems to happen when I stop the Snis for a long time with a breakpoint, while debugging

**Comment by blumzi** [comment]
Obsolete since we no longer use SNIS.
