### ISSUE TITLE
last-unit-server status?

### ISSUE THREAD

**Issue by EastEriq** [blumzi/LAST_WebApi#9]
Can you make a `last-unit-server status` option? With such long startup and stopping times (several minutes, I'll write perhaps a separate ticket about), you never know what is going on. It already occurred me to to start the service minutes after I had stopped it, to find out that it was not yet terminated. You suggested `grep lipp /proc/net/unix` but maybe something more sophisticated and informative could be useful.

**Comment by blumzi** [comment]
Times got much better.  Also, you can now easilly kill the server with Ctrl-C and it dies properly.

When this will become a systemctl service, it will have a proper status.
